### PR TITLE
SRE-13694 - Pin Icinga2 version in Ansible install

### PR DESCRIPTION
**Pull request by kareemstraker-wk**
## JIRA Ticket
https://jira.atl.workiva.net/browse/SRE-13694

## Solution / Approach
Define pinned versions of icinga2
-Unpinned versions of non-core dependencies defined
-Pinned versions of core packages defined

## Reviewer's checklist

- [ ] Verify code meets acceptance requirements
- [ ] Verify quality of code
- [ ] Verify documentation has been updated accordingly
- [ ] Test in a development environment

## Reviewers
@Workiva/sre

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by cristianmartinello-wf** [comment]
+1

**Comment by kareemstraker-wk** [comment]
@diegocarrion-wk @cristianmartinello-wf this PR should have been raised against workiva_fixes, not master, so I'll raise a new one and do the same.

**Comment by kareemstraker-wk** [comment]
@cristianmartinello-wf  still gotta close it, as it was based off master.
new PR at #3

**Pull request closed without merging**
